const quotes = [
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
    "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "The best revenge is massive success. – Frank Sinatra",
    "Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
    "The harder I work, the luckier I get. – Thomas Jefferson",
    "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. – Booker T. Washington",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Success is getting what you want. Happiness is wanting what you get. – W.P. Kinsella",
    "The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr.",
    "To succeed in life, you need two things: ignorance and confidence. – Mark Twain",
    "The best way to predict your future is to create it. – Peter Drucker",
    "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
    "The way you see the world is a reflection of how you see yourself. – Unknown",
    "Life is really simple, but we insist on making it complicated. – Confucius",
    "The only way to have a friend is to be one. – Ralph Waldo Emerson",
    "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams. – Dr. Seuss",
    "The best thing to hold onto in life is each other. – Audrey Hepburn",
    "True love is not about perfection; it is hidden in flaws. – Unknown",
    "The greatest happiness of life is the conviction that we are loved. – Victor Hugo",
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
    "Self-improvement is the key to a better life. – Unknown",
    "Personal growth is not a matter of learning new information but of unlearning old limits. – Alan Cohen",
    "You must do the things you think you cannot do. – Eleanor Roosevelt",
    "To improve is to change; to be perfect is to change often. – Winston Churchill",
    "Your potential is endless. – Unknown",
    "The greatest wealth is to live content with little. – Plato",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "Knowledge speaks, but wisdom listens. – Jimi Hendrix",
    "It is not length of life, but depth of life. – Ralph Waldo Emerson",
    "The wise man does at once what the fool does finally. – Niccolò Machiavelli",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle",
    "Wisdom begins in wonder. – Socrates",
    "In seeking wisdom thou art wise; in imagining that thou hast attained it thou art a fool. – Lord Chesterfield",
    "The greatest wealth is to live content with little. – Plato",
    "The more I know, the more I realize I know nothing. – Socrates",
    "The fool doth think he is wise, but the wise man knows himself to be a fool. – William Shakespeare",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi",
    "Perseverance is not a long race; it is many short races one after the other. – Walter Elliot",
    "Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. The slogan ‘Press On’ has solved and always will solve the problems of the human race. – Calvin Coolidge",
    "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
    "Perseverance is failing 19 times and succeeding the 20th. – Julie Andrews",
    "Success is not measured by what you accomplish, but the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds. – Orison Swett Marden",
    "Energy and persistence conquer all things. – Benjamin Franklin",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
    "Keep your face to the sunshine and you cannot see a shadow. – Helen Keller",
    "The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi",
    "The only thing you take with you when you’re gone is what you leave behind. – John Allston",
    "We make a living by what we get, but we make a life by what we give. – Winston Churchill",
    "Your life is your message to the world. Make sure it’s inspiring. – Unknown",
    "It is not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
    "Live a life that will make you look back with pride. – Unknown",
    "What we do for ourselves dies with us. What we do for others and the world remains and is immortal. – Albert Pine",
    "The greatest use of a life is to spend it on something that will outlast it. – William James",
    "To live in hearts we leave behind is not to die. – Thomas Campbell",
    "The best legacy one can pass on to one’s children and grandchildren is not money or other material things accumulated in one’s life, but rather a legacy of character and faith. – Billy Graham",
    "History will judge us by the difference we make in the everyday lives of children. – Nelson Mandela",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "The more things change, the more they remain the same. – Jean-Baptiste Alphonse Karr",
    "Those who do not remember the past are condemned to repeat it. – George Santayana",
    "The best way to predict your future is to create it. – Peter Drucker",
    "History is written by the victors. – Winston Churchill",
    "You can make a difference with the choices you make. – Unknown",
    "The history of the world is but the biography of great men. – Thomas Carlyle",
    "We make a living by what we get, but we make a life by what we give. – Winston Churchill",
    "Courage is resistance to fear, mastery of fear, not absence of fear. – Mark Twain",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. – William James",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy",
    "It does not do to dwell on dreams and forget to live. – J.K. Rowling",
    "The brave man is not he who does not feel afraid, but he who conquers that fear. – Nelson Mandela",
    "Courage is found in unlikely places. – J.R.R. Tolkien",
    "In the face of fear, you can be brave or you can be scared. You cannot be both. – Unknown",
    "The greatest test of courage on earth is to bear defeat without losing heart. – Robert Green Ingersoll",
    "He who is not courageous enough to take risks will accomplish nothing in life. – Muhammad Ali",
    "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
    "The way you see the world is a reflection of how you see yourself. – Unknown",
    "Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. – Unknown",
    "The only way to have a friend is to be one. – Ralph Waldo Emerson",
    "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. – Ralph Waldo Emerson",
    "The journey of a thousand miles begins with a single step. – Lao Tzu",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou",
    "The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr.",
    "To succeed in life, you need two things: ignorance and confidence. – Mark Twain"
];
  
export default quotes;